In [2]:
import numpy as np
print("numpy loaded successfully")

numpy loaded successfully


In [3]:
np.array(1)  # Output: array(1)
print(type(np.array([1, 2, 3])))  # Output: <class 'numpy.ndarray'>


<class 'numpy.ndarray'>


In [8]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr)  # Output: [[1 2 3]
              #          [4 5 6]]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
print(len(arr))  # Output: 3

2


In [12]:
## attribute of numpy array
print(arr.shape)  # Output: (2, 3)
print(arr.ndim)  # Output: 2
print(arr.size)  # Output: 6

(2, 3)
2
6


In [ ]:
# methods
print(np.arange(0, 10))  # Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


[0 1 2 3 4 5 6 7 8 9]


In [15]:
np.random.rand(3,4)  # Output: 3x4 array of random numbers between 0 and 1

array([[0.24082811, 0.86182187, 0.3196873 , 0.73486777],
       [0.88234351, 0.57037823, 0.31481132, 0.70164861],
       [0.5764873 , 0.96641658, 0.4171308 , 0.16740406]])

In [ ]:
np.random.randint(0,10,10) #start , stop, size
 # Output: 1D array of 10 random integers between 0 and 10

array([1, 2, 6, 2, 6, 9, 0, 1, 2, 2], dtype=int32)