In [31]:
import numpy as np
print("numpy loaded successfully")

numpy loaded successfully


In [32]:
np.array(1)  # Output: array(1)
print(type(np.array([1, 2, 3])))  # Output: <class 'numpy.ndarray'>


<class 'numpy.ndarray'>


In [33]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr)  # Output: [[1 2 3]
              #          [4 5 6]]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [34]:
print(len(arr))  # Output: 3

2


In [35]:
## attribute of numpy array
print(arr.shape)  # Output: (2, 3)
print(arr.ndim)  # Output: 2
print(arr.size)  # Output: 6
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

(2, 3)
2
6
int64


In [36]:
# methods
print(np.arange(0, 10))  # Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


[0 1 2 3 4 5 6 7 8 9]


In [37]:
np.random.rand(3,4)  # Output: 3x4 array of random numbers between 0 and 1

array([[0.08801898, 0.73046333, 0.90002842, 0.59351865],
       [0.353064  , 0.88871884, 0.88204586, 0.27814042],
       [0.70087721, 0.65373278, 0.28063383, 0.58650439]])

In [38]:
np.random.randint(0,10,10) #start , stop, size
 # Output: 1D array of 10 random integers between 0 and 10

array([7, 1, 8, 0, 6, 7, 3, 8, 5, 8], dtype=int32)

In [39]:
#zeroes
np.zeros((2,4,3),dtype=int)  # Output: 2x4x3 array of zeros

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [40]:
np.ones((2,4,3)) # Output: 2x4x3 array of ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
#  min , max, argmax, argmin 
print(arr)
arr =arr.ravel()  # Output: array([1, 2, 3, 4, 5, 6])  # flatten/Convert the array to 1D
min(arr)  # Output: 1  # python function predefined......;min() and max() will not work on 2D array, it will return the minimum and maximum of the first row only.
max(arr)  # Output: 6

np.min(arr)  # Output: 1 #np method will work on 2D array as well and it will return the minimum and maximum of the entire array.

#index finding
np.argmax(arr)  # Output: 5 (index of the maximum value, which is 6) #argmin


[[1 2 3]
 [4 5 6]]


np.int64(5)

In [ ]:
# mean std
print(arr)
arr+arr

list1=[1,2,3,4,5]
list1+list1  # Output: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] #python list concatenation

arr.mean()  # Output: 3.5
arr.std()  # Output: 1.707825127659933


[1 2 3 4 5 6]


np.float64(1.707825127659933)